spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://resume-builder-db.c7oxuegg0cpn.us-east-1.rds.amazonaws.com:3306/resumebuilder}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}

spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Resume#2026DB}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

server.address=0.0.0.0
server.port=8080
