spring.datasource.url=jdbc:mysql://resume-builder-db.c7oxuegg0cpn.us-east-1.rds.amazonaws.com:3306/resumebuilder

spring.datasource.username=admin

spring.datasource.password=Resume#2026DB

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

server.port=8080